package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Options struct {
	Dir      string
	Services []string
	Port     int
	Force    bool
}

func Run(opts Options) error {
	if opts.Dir == "" {
		var err error
		opts.Dir, err = os.Getwd()
		if err != nil {
			return err
		}
	}
	if opts.Port == 0 {
		opts.Port = 8080
	}

	configPath := filepath.Join(opts.Dir, "aegis.yaml")
	envPath := filepath.Join(opts.Dir, ".env.example")

	if !opts.Force {
		if _, err := os.Stat(configPath); err == nil {
			return fmt.Errorf("aegis.yaml already exists (use --force to overwrite)")
		}
	}

	config := buildConfig(opts)
	env := buildEnv(opts)

	if err := os.WriteFile(configPath, []byte(config), 0o644); err != nil {
		return fmt.Errorf("writing aegis.yaml: %w", err)
	}
	if err := os.WriteFile(envPath, []byte(env), 0o644); err != nil {
		return fmt.Errorf("writing .env.example: %w", err)
	}

	fmt.Printf("✓ Created %s\n", configPath)
	fmt.Printf("✓ Created %s\n", envPath)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Printf("  cp .env.example .env\n")
	fmt.Printf("  # Edit .env with your real secrets\n")
	fmt.Printf("  aegis          # start proxy on :%d\n", opts.Port)
	fmt.Printf("  aegis -mode mcp  # or start MCP server\n")
	fmt.Println()
	fmt.Println("Add to .gitignore:")
	fmt.Println("  .env")
	fmt.Println("  aegis.yaml")

	return nil
}

var knownServices = map[string]struct {
	domain     string
	allowlist  string
	credential string
	envVar     string
	header     string
	template   string
}{
	"github": {
		domain:    "api.github.com",
		allowlist: "  - api.github.com",
		envVar:    "GITHUB_TOKEN",
		header:    "Authorization",
		template:  "Bearer ${GITHUB_TOKEN}",
	},
	"slack": {
		domain:    "slack.com",
		allowlist: "  - slack.com\n  - hooks.slack.com",
		envVar:    "SLACK_BOT_TOKEN",
		header:    "Authorization",
		template:  "Bearer ${SLACK_BOT_TOKEN}",
	},
	"stripe": {
		domain:    "api.stripe.com",
		allowlist: "  - api.stripe.com",
		envVar:    "STRIPE_SECRET_KEY",
		header:    "Authorization",
		template:  "Bearer ${STRIPE_SECRET_KEY}",
	},
	"openai": {
		domain:    "api.openai.com",
		allowlist: "  - api.openai.com",
		envVar:    "OPENAI_API_KEY",
		header:    "Authorization",
		template:  "Bearer ${OPENAI_API_KEY}",
	},
	"anthropic": {
		domain:    "api.anthropic.com",
		allowlist: "  - api.anthropic.com",
		envVar:    "ANTHROPIC_API_KEY",
		header:    "x-api-key",
		template:  "${ANTHROPIC_API_KEY}",
	},
	"linear": {
		domain:    "api.linear.app",
		allowlist: "  - api.linear.app",
		envVar:    "LINEAR_API_KEY",
		header:    "Authorization",
		template:  "Bearer ${LINEAR_API_KEY}",
	},
	"notion": {
		domain:    "api.notion.com",
		allowlist: "  - api.notion.com",
		envVar:    "NOTION_TOKEN",
		header:    "Authorization",
		template:  "Bearer ${NOTION_TOKEN}",
	},
	"discord": {
		domain:    "discord.com",
		allowlist: "  - discord.com",
		envVar:    "DISCORD_BOT_TOKEN",
		header:    "Authorization",
		template:  "Bot ${DISCORD_BOT_TOKEN}",
	},
	"jira": {
		domain:    "api.atlassian.com",
		allowlist: "  - api.atlassian.com",
		envVar:    "JIRA_API_TOKEN",
		header:    "Authorization",
		template:  "Bearer ${JIRA_API_TOKEN}",
	},
	"shopify": {
		domain:    "myshopify.com",
		allowlist: "  - myshopify.com",
		envVar:    "SHOPIFY_ACCESS_TOKEN",
		header:    "X-Shopify-Access-Token",
		template:  "${SHOPIFY_ACCESS_TOKEN}",
	},
}

func buildConfig(opts Options) string {
	var sb strings.Builder

	sb.WriteString("# aegis.yaml — generated by `aegis init`\n")
	sb.WriteString("# Add .env and aegis.yaml to .gitignore\n\n")
	sb.WriteString(fmt.Sprintf("port: %d\n\n", opts.Port))
	sb.WriteString("# Optional: write structured NDJSON log to file\n")
	sb.WriteString("# audit_log: ~/.aegis/requests.ndjson\n\n")

	sb.WriteString("allowlist:\n")
	seen := map[string]bool{}
	for _, svc := range opts.Services {
		if s, ok := knownServices[svc]; ok {
			if !seen[s.allowlist] {
				sb.WriteString(s.allowlist + "\n")
				seen[s.allowlist] = true
			}
		} else {
			sb.WriteString(fmt.Sprintf("  # - api.%s.com\n", svc))
		}
	}
	if len(opts.Services) == 0 {
		sb.WriteString("  # - api.github.com\n")
		sb.WriteString("  # - api.stripe.com\n")
	}

	sb.WriteString("\n# Budget guards — prevent runaway agent API spend\n")
	sb.WriteString("# budgets:\n")
	sb.WriteString("#   api.github.com:\n")
	sb.WriteString("#     max_requests_per_hour: 200\n")
	sb.WriteString("#     loop_threshold: 5        # warn if same URL called 5x in 2 min\n\n")

	sb.WriteString("credentials:\n")
	for _, svc := range opts.Services {
		if s, ok := knownServices[svc]; ok {
			sb.WriteString(fmt.Sprintf("  %s:\n", s.domain))
			sb.WriteString(fmt.Sprintf("    header: %s\n", s.header))
			sb.WriteString(fmt.Sprintf("    template: \"%s\"\n\n", s.template))
		}
	}
	if len(opts.Services) == 0 {
		sb.WriteString("  # api.github.com:\n")
		sb.WriteString("  #   header: Authorization\n")
		sb.WriteString("  #   template: \"Bearer ${GITHUB_TOKEN}\"\n")
	}

	return sb.String()
}

func buildEnv(opts Options) string {
	var sb strings.Builder
	sb.WriteString("# .env.example — copy to .env and fill in real values\n")
	sb.WriteString("# NEVER commit .env to version control\n\n")
	for _, svc := range opts.Services {
		if s, ok := knownServices[svc]; ok {
			sb.WriteString(fmt.Sprintf("%s=your_%s_here\n", s.envVar, strings.ToLower(s.envVar)))
		}
	}
	if len(opts.Services) == 0 {
		sb.WriteString("# GITHUB_TOKEN=ghp_...\n")
		sb.WriteString("# STRIPE_SECRET_KEY=sk_live_...\n")
	}
	return sb.String()
}

